---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: chart-storage-efs-pv
  spec:
    capacity:
      storage: 10Gi
    accessModes:
      - ReadWriteOnce
    nfs:
      # Create this first!
      server: {{ .Values.chartmuseumStorage.efs.server }}
      path: "/chartmuseum"