---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: {{ template "fullname" . }}
      heritage: {{ .Release.Service | quote }}
      release: {{ .Release.Name | quote }}
      version: 1.0.0
    name: chart-storage
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    volumeName: chart-storage-efs-pv