---
apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      configmap.fabric8.io/update-on-change: {{ template "fullname" . }}
      fabric8.io/target-platform: kubernetes
    labels:
      app: {{ template "fullname" . }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: {{ .Release.Name | quote }}
      heritage: {{ .Release.Service | quote }}
      version: 1.0.0
    name: {{ template "fullname" . }}
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
        version: 1.0.0
    template:
      metadata:
        annotations:
          configmap.fabric8.io/update-on-change: {{ template "fullname" . }}
          fabric8.io/target-platform: kubernetes
        labels:
          app: {{ template "fullname" . }}
          chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
          release: {{ .Release.Name | quote }}
          heritage: {{ .Release.Service | quote }}
          version: 1.0.0
      spec:
        containers:
        - name: {{ template "fullname" . }}
          env:
          - name: PROJECT_NAMESPACE
            value: ${PROJECT_NAMESPACE}
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: KUBERNETES_MASTER
            value: https://kubernetes.default:443
          - name: STORAGE
            value: local
          - name: ALLOW_OVERWRITE
            value: "true"
          image: "{{ .Values.chartmuseum.image.name }}:{{ .Values.chartmuseum.image.tag }}"
          imagePullPolicy: {{ .Values.chartmuseum.image.pullPolicy }}
          args:
          - --port=8080
          - --storage-local-rootdir={{ .Values.chartmuseum.config.localStoragePath }}
          ports:
          - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
          - mountPath: {{ .Values.chartmuseum.config.localStoragePath }}
            name: chart-storage
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 80m
              memory: 64Mi  
        volumes:
        - name: chart-storage
          persistentVolumeClaim:
            claimName: chart-storage