kubernetes:
  host: https://kubernetes.default:443

chartmuseum:
  namespace: tools
  forecastle: {}
    # icon: https://cdn-images-1.medium.com/max/521/0*D__TQ7qMdoq3Y7kP.png
    # expose: "true"
  service:
    ingressClass: internal-ingress
  labels:
    version: 0.5.1
    group: com.stakater.platform
    provider: stakater
  image:
    name: chartmuseum/chartmuseum
    tag: v0.5.1
    pullPolicy: IfNotPresent
  config:
    localStoragePath: /storage
    allowOverwrite: "true"
    auth:
      enabled: true
      username: "stakater"
      password: "somepassword"
      allowAnonymousGet: "true"
      